# MGT-499 Statistics and Data Science - Individual Assignment

In [551]:
# Importing all the libraries I am using
import numpy as np
import math
import pandas as pd
#import my_module # here I can add all my functions
import os #We import os in order to change/specify our working directory. .chdir(path) allows to change the working directory to "path" while .getcwd() returns a string representing the current working directory (you could also use pwd)
import plotly.express as px #interractive boxplots
import matplotlib.pyplot as plt 
import seaborn as sb
import bokeh.io # for more visual demonstration
import bokeh.models #for more visual demonstration
import bokeh.plotting #for more visual demonstration
#df_gps = pd.read_stata("data/global_preference_survey.dta") # Import dataset on Global Preference Survey from local folder

This notebook contains the individual assignment for the class MGT-499 Statistics and Data Science. Important information:
- **Content**: the assignment is divided in two main parts, namely data cleaning (2 datasets) and Exploratory Data Analysis, for a total of 13 main questions (see table of contents). Some of these main questions are divided in sub questions. In the first part, the questions are very specific, while in the second part they are more open.
- **Deadline**: Tuesday 8th of November at 23:59. 
- **Final Output**: a Jupyter notebook, which we (teachers) can run. 
- **Answering the Questions**: you will find the questions in markdown cells below. Under each of these cells, you will find a cell / cells for answers. Type there your answer. For the answer to be correct, the cell with the answer must run without error (unless specified). You can use markdown cells for the answers that require text.
- **Submission**: submit the assignment on Moodle, under [Individual Assignment](https://moodle.epfl.ch/mod/assign/view.php?id=1222846)

## Content
- [Polity5 Dataset](#polity5)  
    - [Question 1: Import the data and get a first glance](#question1)
    - [Question 2: Select some variables](#question2)
    - [Question 3: Missing Values](#question3)
    - [Question 4: Check Polity2](#question4)
- [Quality of Government (QOG) Environmental Indicators Dataset](#qog)  
    - [Question 5: Import the data and do few fixes](#question5)
    - [Question 6: Merge QOG and Polity5 ... first attempt](#question6)
    - [Question 7: Merge QOG and Polity5 ... second attempt](#question7)
    - [Question 8: Clean the merged dataframe](#question8)
- [Exploratory Data Analysis](#eda)
    - [Question 9: Selecting the ingredients for the recipe (how I select the variables)](#question9)  
    - [Question 10: Picking the right quantity of each ingredient (how I select my sample)](#question10)
    - [Question 11: Tasting and preparing the ingredients (univariate analysis)](#question11)
    - [Question 12: Cooking the ingredients together (bivariate analysis)](#question12)
    - [Question 13: Tasting the new recipe (conclusion)](#question13)

## Polity5 data <a class="anchor" id="polity5"></a>

Polity5 is a widely used democracy scale. The raw data as well as the codebook are available [here](http://www.systemicpeace.org/inscrdata.html). For this assignment, we have modified a bit the original version, for example we have added the iso3 code for countries to make you save time. You can find the modified version [here](https://raw.githubusercontent.com/edoardochiarotti/class_datascience/main/Notebooks/Assignment/individual_assignment/data/polity2_iso3.csv).

### Question 1: import the data and get a first glance <a class="anchor" id="question1"></a>

1a) Import the csv 'polity2_iso3.csv' (file provided in the link [here](https://raw.githubusercontent.com/edoardochiarotti/class_datascience/main/Notebooks/Assignment/individual_assignment/data/polity2_iso3.csv)) as a panda dataframe (ignore the warning message) **(1 point)**

In [552]:
url = "https://raw.githubusercontent.com/edoardochiarotti/class_datascience/main/Notebooks/Assignment/individual_assignment/data/polity2_iso3.csv"
data = pd.read_csv(url,low_memory=False) #use low memeory false since there are different datatypes in the same column
type(data)

pandas.core.frame.DataFrame

1b) Display the first 10 rows **(1 point)**

In [553]:
data.head(10) #with the head function I can decide how many rows I want to display

,iso3,year,p5,cyear,ccode,scode,country,flag,fragment,democ,...,interim,bmonth,bday,byear,bprec,post,change,d5,sf,regtrans
0,NaN,1800,0,2711800,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,1,1,1800,1,-7,88,1,NaN,NaN
1,NaN,1800,0,7301800,730,KOR,Korea,0,NaN,5,...,NaN,1,1,1800,1,1,88,1,NaN,NaN
2,NaN,1800,0,2451800,245,BAV,Bavaria,0,NaN,0,...,NaN,1,1,1800,1,-10,88,1,NaN,NaN
3,NaN,1801,0,7301801,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1801,0,2711801,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,1801,0,2451801,245,BAV,Bavaria,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,1802,0,7301802,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,1802,0,2711802,271,WRT,Wuerttemburg,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1802,0,2451802,245,BAV,Bavaria,0,NaN,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,1803,0,7301803,730,KOR,Korea,0,NaN,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

1c) Display the data types of all the variables included in the data **(1 point)**

In [554]:
data.dtypes #shows the type of data from each column

iso3         object
year          int64
p5            int64
cyear         int64
ccode         int64
scode        object
country      object
flag          int64
fragment    float64
democ         int64
autoc         int64
polity        int64
polity2     float64
durable      object
xrreg         int64
xrcomp        int64
xropen        int64
xconst        int64
parreg        int64
parcomp       int64
exrec       float64
exconst       int64
polcomp     float64
prior        object
emonth       object
eday         object
eyear        object
eprec        object
interim      object
bmonth       object
bday         object
byear        object
bprec        object
post         object
change       object
d5           object
sf           object
regtrans     object
dtype: object

1d) By looking at your answer in 1c, what is the difference between the different types of variables? Why the type of some variables is defined as object? **(1 point)**

My data shows 3 different types of variables: 
- object -> since I use panda, instead of string it shows me object. It refers to strings, as well as mixed columns of numeric characters and strings
- int64 -> the column holds only numeric characters
- float64 -> the column holds numeric characters, as well as blanks like "NaN"

-> The index64 stands for the memory allocated to the character

### Question 2. Select some variables <a class="anchor" id="question2"></a>

2a) Create a subset dataframe that contains the variables 'iso3', 'country', 'year', 'polity2' and display it **(1 point)**

In [555]:
# 2a) subset creation for iso3', 'country', 'year', 'polity2
subset_1=data.loc[:,["iso3","country","year","polity2"]]
print(subset_1)

      iso3       country  year  polity2
0      NaN  Wuerttemburg  1800     -7.0
1      NaN         Korea  1800      1.0
2      NaN       Bavaria  1800    -10.0
3      NaN         Korea  1801      1.0
4      NaN  Wuerttemburg  1801     -7.0
...    ...           ...   ...      ...
17569  ZWE      Zimbabwe  2014      4.0
17570  ZWE      Zimbabwe  2015      4.0
17571  ZWE      Zimbabwe  2016      4.0
17572  ZWE      Zimbabwe  2017      4.0
17573  ZWE      Zimbabwe  2018      4.0

[17574 rows x 4 columns]

2b) Display the type of the variable "year" **(1 point)**

In [556]:
# 2b) display type of the single column "year"
subset_1["year"].dtypes

dtype('int64')

2c) Convert the variable "year" to string **(1 point)**
<br>
Hint: if you get a warning message of the type "SettingWithCopyWarning", it is because you did not subset the data in the right way. Go back to your class notes and check the different ways to subset a dataframe, and try again. If you do it correctly, you will not get the warning message.

In [557]:
#  2c) convert integer into string -> object sicne I use panda

subset_1["year"]=subset_1["year"].astype(str) 
print(subset_1.dtypes)# checking if my operation worked

iso3        object
country     object
year        object
polity2    float64
dtype: object

### Question 3: Missing Values <a class="anchor" id="question3"></a>

3a) Subset the rows that have iso3 missing and display **(1 point)**

In [558]:
#  3a) missing iso3 subset

#print(subset_1.isna().sum()) #check which columns have NaN's 

subset_iso3=subset_1.loc[subset_1["iso3"].isna()] #create new subset_iso3

print(subset_iso3)
subset_iso3=subset_iso3.copy()

     iso3       country  year  polity2
0     NaN  Wuerttemburg  1800     -7.0
1     NaN         Korea  1800      1.0
2     NaN       Bavaria  1800    -10.0
3     NaN         Korea  1801      1.0
4     NaN  Wuerttemburg  1801     -7.0
...   ...           ...   ...      ...
1272  NaN    Montenegro  2018      9.0
1273  NaN   Sudan-North  2018     -4.0
1274  NaN       Vietnam  2018     -7.0
1275  NaN      Ethiopia  2018      1.0
1276  NaN        Serbia  2018      8.0

[1270 rows x 4 columns]

3b) Display the countries that have missing iso3. What can you tell by looking at them? Any similarities? **(1 point)**

In [559]:
# 3b) countries with missing iso3
subset_iso3.country.unique()
'''
these countries show different patterns. 
-> One group shows that they are states within a country - for example Bavaria or Saxony are states within Germany, while Tuscany is within Italy
-> Another group shows countries that are not existing anymore like Germany West, Czechoslovakia, Yugoslavia since there were annexed and other parts became independent countries
'''

'\nthese countries show different patterns. \n-> One group shows that they are states within a country - for example Bavaria or Saxony are states within Germany, while Tuscany is within Italy\n-> Another group shows countries that are not existing anymore like Germany West, Czechoslovakia, Yugoslavia since there were annexed and other parts became independent countries\n'

3c) Display the countries with missing iso3 from 2011. **(1 point)**

In [560]:
#  3c) displays all countries of 2011 onwards that don't have an iso code
subset_iso3["year"]= subset_iso3["year"].astype(int) #transform year into interger so it can be read as a numerical number -> needed for comaprison <,>,=
subset_iso3[(subset_iso3["iso3"].isna() & (subset_iso3["year"] >2010))].country.unique()  
#print(subset_iso3)

array(['Montenegro', 'Serbia', 'Ethiopia', 'Sudan-North', 'Vietnam'],
      dtype=object)

3d) Display the rows for which the column "country" contains the word "Serbia". By looking at the result, can you tell what happened to Serbia in 2006? **(1 point)**
<br>
Hint: the most general way of doing this is to use a combination of re.search and list comprehension. To display the full subset, you can use print(df.to_string()).

In [561]:
# 3d) Serbia dive in
subset_serbia=subset_iso3.loc[subset_iso3["country"].str.contains("Serbia")] #extract Serbia from my subset_dataset
subset_serbia[(subset_serbia["year"] == 2006) & (subset_serbia["country"]== "Serbia")] #only selecting Serbia in 2006
print(subset_serbia.to_string()) #see bigger picture to compare
#in 2006 Serbia and Montenegro split - Montenegro was annexed of Serbia and Serbian's polity factor jumped from 6 to 8.

     iso3                country  year  polity2
224   NaN                 Serbia  1830     -7.0
230   NaN                 Serbia  1831     -7.0
252   NaN                 Serbia  1832     -7.0
261   NaN                 Serbia  1833     -7.0
272   NaN                 Serbia  1834     -7.0
286   NaN                 Serbia  1835     -7.0
295   NaN                 Serbia  1836     -7.0
301   NaN                 Serbia  1837     -7.0
318   NaN                 Serbia  1838      2.0
333   NaN                 Serbia  1839      2.0
344   NaN                 Serbia  1840      2.0
357   NaN                 Serbia  1841      2.0
363   NaN                 Serbia  1842      2.0
369   NaN                 Serbia  1843      2.0
387   NaN                 Serbia  1844      2.0
394   NaN                 Serbia  1845      2.0
410   NaN                 Serbia  1846      2.0
420   NaN                 Serbia  1847      2.0
429   NaN                 Serbia  1848      2.0
439   NaN                 Serbia  1849      2.0
450   NaN                 Serbia  1850      2.0
467   NaN                 Serbia  1851      2.0
475   NaN                 Serbia  1852      2.0
482   NaN                 Serbia  1853      2.0
492   NaN                 Serbia  1854      2.0
502   NaN                 Serbia  1855      2.0
523   NaN                 Serbia  1856      2.0
533   NaN                 Serbia  1857      2.0
542   NaN                 Serbia  1858     -9.0
553   NaN                 Serbia  1859     -9.0
572   NaN                 Serbia  1860     -4.0
575   NaN                 Serbia  1861      0.0
583   NaN                 Serbia  1862      0.0
593   NaN                 Serbia  1863      0.0
601   NaN                 Serbia  1864      0.0
608   NaN                 Serbia  1865      0.0
611   NaN                 Serbia  1866      0.0
623   NaN                 Serbia  1867      0.0
628   NaN                 Serbia  1868     -3.0
637   NaN                 Serbia  1869     -5.0
642   NaN                 Serbia  1870     -5.0
651   NaN                 Serbia  1871     -5.0
652   NaN                 Serbia  1872     -5.0
657   NaN                 Serbia  1873     -5.0
660   NaN                 Serbia  1874     -5.0
663   NaN                 Serbia  1875     -5.0
665   NaN                 Serbia  1876     -5.0
669   NaN                 Serbia  1877     -5.0
671   NaN                 Serbia  1878     -5.0
673   NaN                 Serbia  1879     -5.0
676   NaN                 Serbia  1880     -5.0
680   NaN                 Serbia  1881     -5.0
684   NaN                 Serbia  1882     -5.0
686   NaN                 Serbia  1883     -5.0
690   NaN                 Serbia  1884     -5.0
693   NaN                 Serbia  1885     -5.0
694   NaN                 Serbia  1886     -5.0
697   NaN                 Serbia  1887     -5.0
700   NaN                 Serbia  1888     -5.0
704   NaN                 Serbia  1889     -5.0
708   NaN                 Serbia  1890     -5.0
709   NaN                 Serbia  1891     -5.0
714   NaN                 Serbia  1892     -5.0
715   NaN                 Serbia  1893     -5.0
718   NaN                 Serbia  1894     -5.0
722   NaN                 Serbia  1895     -5.0
724   NaN                 Serbia  1896     -5.0
729   NaN                 Serbia  1897     -5.0
730   NaN                 Serbia  1898     -5.0
733   NaN                 Serbia  1899     -5.0
737   NaN                 Serbia  1900     -5.0
739   NaN                 Serbia  1901     -5.0
743   NaN                 Serbia  1902     -5.0
745   NaN                 Serbia  1903      4.0
748   NaN                 Serbia  1904      4.0
749   NaN                 Serbia  1905      4.0
751   NaN                 Serbia  1906      4.0
753   NaN                 Serbia  1907      4.0
755   NaN                 Serbia  1908      4.0
758   NaN                 Serbia  1909      4.0
759   NaN                 Serbia  1910      4.0
761   NaN                 Serbia  1911      4.0
762   NaN                 Serbia  1912      4.0
763   NaN                 Serbia  1913      4.0
764   NaN                 Serbia  1914      4.0
765   NaN                 Serbia  1915      NaN
766   NaN                 Serbia  1916      NaN
767   NaN                 Serbia  1917      4.0
769   NaN                 Serbia  1918      5.0
773   NaN                 Serbia  1919      6.0
774   NaN                 Serbia  1920      7.0
1201  NaN  Serbia and Montenegro  2003      6.0
1205  NaN  Serbia and Montenegro  2004      6.0
1207  NaN  Serbia and Montenegro  2005      6.0
1212  NaN  Serbia and Montenegro  2006      6.0
1213  NaN                 Serbia  2006      8.0
1217  NaN                 Serbia  2007      8.0
1218  NaN                 Serbia  2008      8.0
1224  NaN                 Serbia  2009      8.0
1228  NaN                 Serbia  2010      8.0
1231  NaN                 Serbia  2011      8.0
1238  NaN                 Serbia  2012      8.0
1247  NaN                 Serbia  2013      8.0
1248  NaN                 Serbia  2014      8.0
1254  NaN                 Serbia  2015      8.0
1263  NaN                 Serbia  2016      8.0
1269  NaN                 Serbia  2017      8.0
1276  NaN                 Serbia  2018      8.0

3e) Write a function that does the operation in 3d and use it to display the subset that has the word "sudan" (all lower cap) in country. Then do the same for the word "vietnam" (all lower cap). **(1 point)**
<br>
Hint: options of functions can be very useful.

In [562]:
# function for Serbia dive in
def subsetting_country(country_name):
    return subset_iso3.loc[subset_iso3["country"].str.contains (country_name,case=False)] #same as in 3e, additionally define with case the input of lower letters
subsetting_country("sudan")

     iso3      country  year  polity2
1234  NaN  Sudan-North  2011     -4.0
1241  NaN  Sudan-North  2012     -4.0
1244  NaN  Sudan-North  2013     -4.0
1252  NaN  Sudan-North  2014     -4.0
1256  NaN  Sudan-North  2015     -4.0
1262  NaN  Sudan-North  2016     -4.0
1270  NaN  Sudan-North  2017     -4.0
1273  NaN  Sudan-North  2018     -4.0

3f) Replace nan values in iso3 with correct iso3 for the 5 countries found in 3c from 2011 onwards, and display the subset with the fixed values to check that everything worked. **(1 point)**
<br>
Hint: the correct iso3 for these 5 countries are "ETH","MNE","SRB","SDN","VNM".

In [563]:
# 3f) correcting iso codes

print(subset_iso3.to_string())

for index in subset_iso3.index:
    if subset_iso3.loc[index, 'country'] == 'Ethiopia' and subset_iso3.loc[index,"year"] >2010:
        subset_iso3.loc[index,'iso3']="ETH" 
    if subset_iso3.loc[index, 'country'] == 'Montenegro' and subset_iso3.loc[index,"year"] >2010:
        subset_iso3.loc[index,'iso3']="MNE" 
    if subset_iso3.loc[index, 'country'] == 'Serbia' and subset_iso3.loc[index,"year"] >2010:
        subset_iso3.loc[index,'iso3']="SRB" 
    if subset_iso3.loc[index, 'country'] == 'Sudan-North' and subset_iso3.loc[index,"year"] >2010:
        subset_iso3.loc[index,'iso3']="SDN" 
    if subset_iso3.loc[index, 'country'] == 'Vietnam' and subset_iso3.loc[index,"year"] >2010:
        subset_iso3.loc[index,'iso3']="VNM" 


print(subset_iso3.to_string())

     iso3                country  year  polity2
0     NaN           Wuerttemburg  1800     -7.0
1     NaN                  Korea  1800      1.0
2     NaN                Bavaria  1800    -10.0
3     NaN                  Korea  1801      1.0
4     NaN           Wuerttemburg  1801     -7.0
5     NaN                Bavaria  1801    -10.0
6     NaN                  Korea  1802      1.0
7     NaN           Wuerttemburg  1802     -7.0
8     NaN                Bavaria  1802    -10.0
9     NaN                  Korea  1803      1.0
10    NaN                Bavaria  1803    -10.0
11    NaN           Wuerttemburg  1803     -7.0
12    NaN                Bavaria  1804    -10.0
13    NaN                  Korea  1804      1.0
14    NaN           Wuerttemburg  1804     -7.0
15    NaN           Wuerttemburg  1805     -7.0
16    NaN                  Korea  1805      1.0
17    NaN                Bavaria  1805    -10.0
18    NaN                Bavaria  1806    -10.0
19    NaN           Wuerttemburg  1806     -7.0
20    NaN                  Korea  1806      1.0
21    NaN                 Saxony  1806    -10.0
22    NaN                  Korea  1807      1.0
23    NaN                 Saxony  1807    -10.0
24    NaN                Bavaria  1807    -10.0
25    NaN           Wuerttemburg  1807     -7.0
26    NaN                 Saxony  1808    -10.0
27    NaN                Bavaria  1808    -10.0
28    NaN                  Korea  1808      1.0
29    NaN           Wuerttemburg  1808     -7.0
30    NaN                  Korea  1809      1.0
31    NaN                Bavaria  1809    -10.0
32    NaN           Wuerttemburg  1809     -7.0
33    NaN                 Saxony  1809    -10.0
34    NaN           Wuerttemburg  1810     -7.0
35    NaN                Bavaria  1810    -10.0
36    NaN                 Saxony  1810    -10.0
37    NaN                  Korea  1810      1.0
38    NaN                Bavaria  1811    -10.0
39    NaN           Wuerttemburg  1811     -7.0
40    NaN                 Saxony  1811    -10.0
41    NaN                  Korea  1811      1.0
42    NaN                 Saxony  1812    -10.0
43    NaN                Bavaria  1812    -10.0
44    NaN           Wuerttemburg  1812     -7.0
45    NaN                  Korea  1812      1.0
46    NaN                 Saxony  1813      NaN
47    NaN           Wuerttemburg  1813     -7.0
48    NaN                  Korea  1813      1.0
49    NaN                Bavaria  1813    -10.0
50    NaN                 Saxony  1814      NaN
51    NaN                Bavaria  1814    -10.0
52    NaN                  Korea  1814      1.0
53    NaN           Wuerttemburg  1814     -7.0
54    NaN                  Parma  1815    -10.0
55    NaN                  Korea  1815      1.0
56    NaN                Tuscany  1815    -10.0
57    NaN               Sardinia  1815    -10.0
58    NaN                 Modena  1815    -10.0
59    NaN                Bavaria  1815    -10.0
60    NaN                 Saxony  1815    -10.0
61    NaN           Wuerttemburg  1815     -7.0
62    NaN           Wuerttemburg  1816     -7.0
63    NaN                Tuscany  1816    -10.0
64    NaN           Two Sicilies  1816    -10.0
65    NaN                  Korea  1816      1.0
66    NaN               Sardinia  1816    -10.0
67    NaN                Bavaria  1816    -10.0
68    NaN                 Saxony  1816    -10.0
69    NaN                 Modena  1816    -10.0
70    NaN                  Parma  1816    -10.0
71    NaN                  Parma  1817    -10.0
72    NaN               Sardinia  1817    -10.0
73    NaN           Wuerttemburg  1817     -7.0
74    NaN           Two Sicilies  1817    -10.0
75    NaN                  Korea  1817      1.0
76    NaN                Bavaria  1817    -10.0
77    NaN                 Modena  1817    -10.0
78    NaN                 Saxony  1817    -10.0
79    NaN                Tuscany  1817    -10.0
80    NaN           Two Sicilies  1818    -10.0
81    NaN                Tuscany  1818    -10.0
82    NaN                 Modena  1818    -10.0
83    NaN                Bavaria  1818     -9.0
84    NaN           Wuerttemburg  1818     -7.0
85    NaN                 Saxony  1818    -10.0
86    NaN                  Parma  1818    -10.0
87    NaN                  Korea  1818      1.0
88    NaN               Sardinia  1818    -10.0
89    NaN                  Baden  1819     -7.0
90    NaN                 Saxony  1819    -10.0
91    NaN           Two Sicilies  1819    -10.0
92    NaN           Wuerttemburg  1819     -4.0
93    NaN                Bavaria  1819     -9.0
94    NaN                 Modena  1819    -10.0
95    NaN                  Parma  1819    -10.0
96    NaN               Sardinia  1819    -10.0
97    NaN                  Korea  1819      1.0
98    NaN                Tuscany  1819    -10.0
99    NaN                  Parma  1820    -10.0
100   NaN                  Korea  1820      1.0
101   NaN                 Saxony  1820    -10.0
102   NaN               Sardinia  1820    -10.0
103   NaN                 Modena  1820    -10.0
104   NaN                Tuscany  1820    -10.0
105   NaN           Wuerttemburg  1820     -4.0
106   NaN           Two Sicilies  1820     -6.0
107   NaN                  Baden  1820     -7.0
108   NaN                Bavaria  1820     -9.0
109   NaN                  Parma  1821    -10.0
110   NaN           Two Sicilies  1821    -10.0
111   NaN                Bavaria  1821     -9.0
112   NaN          Gran Colombia  1821     -1.0
113   NaN                 Saxony  1821    -10.0
114   NaN                  Baden  1821     -7.0
115   NaN           Wuerttemburg  1821     -4.0
116   NaN                Tuscany  1821    -10.0
117   NaN                  Korea  1821      1.0
118   NaN                 Modena  1821    -10.0
119   NaN               Sardinia  1821    -10.0
120   NaN                Bavaria  1822     -9.0
121   NaN                  Parma  1822    -10.0
122   NaN                  Baden  1822     -7.0
123   NaN                Tuscany  1822    -10.0
124   NaN                 Modena  1822    -10.0
125   NaN                 Saxony  1822    -10.0
126   NaN          Gran Colombia  1822     -1.0
127   NaN                  Korea  1822      1.0
128   NaN               Sardinia  1822    -10.0
129   NaN           Wuerttemburg  1822     -4.0
130   NaN           Two Sicilies  1822    -10.0
131   NaN                  Korea  1823      1.0
132   NaN                Tuscany  1823    -10.0
133   NaN                 Modena  1823    -10.0
134   NaN               Sardinia  1823    -10.0
135   NaN                  Baden  1823     -7.0
136   NaN           Two Sicilies  1823    -10.0
137   NaN          Gran Colombia  1823     -1.0
138   NaN                  Parma  1823    -10.0
139   NaN                 Saxony  1823    -10.0
140   NaN           Wuerttemburg  1823     -4.0
141   NaN                Bavaria  1823     -9.0
142   NaN                  Baden  1824     -7.0
143   NaN          Gran Colombia  1824     -1.0
144   NaN           Wuerttemburg  1824     -4.0
145   NaN                 Modena  1824    -10.0
146   NaN                  Korea  1824      1.0
147   NaN     United Province CA  1824      2.0
148   NaN                Tuscany  1824    -10.0
149   NaN               Sardinia  1824    -10.0
150   NaN           Two Sicilies  1824    -10.0
151   NaN                Bavaria  1824     -9.0
152   NaN                 Saxony  1824    -10.0
153   NaN                  Parma  1824    -10.0
154   NaN     United Province CA  1825      2.0
155   NaN           Wuerttemburg  1825     -4.0
156   NaN                  Parma  1825    -10.0
157   NaN                Bavaria  1825     -9.0
158   NaN                 Saxony  1825    -10.0
159   NaN          Gran Colombia  1825     -1.0
160   NaN           Two Sicilies  1825    -10.0
161   NaN                 Modena  1825    -10.0
162   NaN                Tuscany  1825    -10.0
163   NaN                  Korea  1825      1.0
164   NaN               Sardinia  1825    -10.0
165   NaN                  Baden  1825     -7.0
166   NaN                  Parma  1826    -10.0
167   NaN                  Korea  1826      1.0
168   NaN           Wuerttemburg  1826     -4.0
169   NaN          Gran Colombia  1826     -1.0
170   NaN                  Baden  1826     -7.0
171   NaN           Two Sicilies  1826    -10.0
172   NaN     United Province CA  1826      2.0
173   NaN                 Modena  1826    -10.0
174   NaN               Sardinia  1826    -10.0
175   NaN                 Saxony  1826    -10.0
176   NaN                Bavaria  1826     -9.0
177   NaN                Tuscany  1826    -10.0
178   NaN               Sardinia  1827    -10.0
179   NaN           Two Sicilies  1827    -10.0
180   NaN     United Province CA  1827      2.0
181   NaN                  Baden  1827     -7.0
182   NaN                 Modena  1827    -10.0
183   NaN                 Saxony  1827    -10.0
184   NaN                  Korea  1827      1.0
185   NaN                  Parma  1827    -10.0
186   NaN                Bavaria  1827     -9.0
187   NaN                Tuscany  1827    -10.0
188   NaN          Gran Colombia  1827     -1.0
189   NaN           Wuerttemburg  1827     -4.0
190   NaN           Wuerttemburg  1828     -4.0
191   NaN               Sardinia  1828    -10.0
192   NaN                  Baden  1828     -7.0
193   NaN     United Province CA  1828      2.0
194   NaN                  Korea  1828      1.0
195   NaN                 Saxony  1828    -10.0
196   NaN           Two Sicilies  1828    -10.0
197   NaN                 Modena  1828    -10.0
198   NaN                Bavaria  1828     -9.0
199   NaN          Gran Colombia  1828     -5.0
200   NaN                  Parma  1828    -10.0
201   NaN                Tuscany  1828    -10.0
202   NaN           Wuerttemburg  1829     -4.0
203   NaN           Two Sicilies  1829    -10.0
204   NaN                Bavaria  1829     -9.0
205   NaN          Gran Colombia  1829     -5.0
206   NaN                  Parma  1829    -10.0
207   NaN                  Baden  1829     -7.0
208   NaN                Tuscany  1829    -10.0
209   NaN               Sardinia  1829    -10.0
210   NaN                  Korea  1829      1.0
211   NaN                 Saxony  1829    -10.0
212   NaN                 Modena  1829    -10.0
213   NaN     United Province CA  1829      2.0
214   NaN          Gran Colombia  1830     -5.0
215   NaN               Sardinia  1830    -10.0
216   NaN           Two Sicilies  1830    -10.0
217   NaN           Wuerttemburg  1830     -4.0
218   NaN     United Province CA  1830      2.0
219   NaN                 Saxony  1830    -10.0
220   NaN                Bavaria  1830     -9.0
221   NaN                 Modena  1830    -10.0
222   NaN                  Baden  1830     -7.0
223   NaN                  Parma  1830    -10.0
224   NaN                 Serbia  1830     -7.0
225   NaN                  Korea  1830      1.0
226   NaN                Tuscany  1830    -10.0
227   NaN           Wuerttemburg  1831     -4.0
228   NaN          Gran Colombia  1831     -5.0
229   NaN           Two Sicilies  1831    -10.0
230   NaN                 Serbia  1831     -7.0
231   NaN                  Baden  1831     -7.0
232   NaN     United Province CA  1831      2.0
233   NaN                  Parma  1831    -10.0
234   NaN               Sardinia  1831    -10.0
235   NaN                Tuscany  1831    -10.0
236   NaN                Bavaria  1831     -9.0
237   NaN                 Saxony  1831     -7.0
238   NaN                 Modena  1831    -10.0
239   NaN                  Korea  1831      1.0
240   NaN                  Parma  1832    -10.0
241   NaN               Sardinia  1832    -10.0
242   NaN                 Saxony  1832     -7.0
243   NaN                 Modena  1832    -10.0
244   NaN           Wuerttemburg  1832     -4.0
245   NaN                  Baden  1832     -7.0
246   NaN                  Korea  1832      1.0
247   NaN                Tuscany  1832    -10.0
248   NaN           Two Sicilies  1832    -10.0
249   NaN          Gran Colombia  1832     -5.0
250   NaN                Bavaria  1832     -9.0
251   NaN     United Province CA  1832      2.0
252   NaN                 Serbia  1832     -7.0
253   NaN     United Province CA  1833      2.0
254   NaN               Sardinia  1833    -10.0
255   NaN           Wuerttemburg  1833     -4.0
256   NaN                  Parma  1833    -10.0
257   NaN                  Baden  1833     -7.0
258   NaN                  Korea  1833      1.0
259   NaN           Two Sicilies  1833    -10.0
260   NaN                 Modena  1833    -10.0
261   NaN                 Serbia  1833     -7.0
262   NaN                Tuscany  1833    -10.0
263   NaN                 Saxony  1833     -7.0
264   NaN                Bavaria  1833     -9.0
265   NaN                  Baden  1834     -7.0
266   NaN                  Korea  1834      1.0
267   NaN                 Saxony  1834     -7.0
268   NaN                 Modena  1834    -10.0
269   NaN               Sardinia  1834    -10.0
270   NaN           Two Sicilies  1834    -10.0
271   NaN                Tuscany  1834    -10.0
272   NaN                 Serbia  1834     -7.0
273   NaN           Wuerttemburg  1834     -4.0
274   NaN                  Parma  1834    -10.0
275   NaN                Bavaria  1834     -9.0
276   NaN     United Province CA  1834      2.0
277   NaN                Bavaria  1835     -9.0
278   NaN                  Baden  1835     -7.0
279   NaN               Sardinia  1835    -10.0
280   NaN                Tuscany  1835    -10.0
281   NaN           Wuerttemburg  1835     -4.0
282   NaN           Two Sicilies  1835    -10.0
283   NaN                 Modena  1835    -10.0
284   NaN                  Parma  1835    -10.0
285   NaN                 Saxony  1835     -7.0
286   NaN                 Serbia  1835     -7.0
287   NaN     United Province CA  1835      2.0
288   NaN                  Korea  1835      1.0
289   NaN               Sardinia  1836    -10.0
290   NaN                  Korea  1836      1.0
291   NaN                  Parma  1836    -10.0
292   NaN           Wuerttemburg  1836     -4.0
293   NaN                  Baden  1836     -7.0
294   NaN     United Province CA  1836      2.0
295   NaN                 Serbia  1836     -7.0
296   NaN                 Saxony  1836     -7.0
297   NaN                Tuscany  1836    -10.0
298   NaN           Two Sicilies  1836    -10.0
299   NaN                Bavaria  1836     -9.0
300   NaN                 Modena  1836    -10.0
301   NaN                 Serbia  1837     -7.0
302   NaN                 Saxony  1837     -7.0
303   NaN           Wuerttemburg  1837     -4.0
304   NaN               Sardinia  1837    -10.0
305   NaN                 Modena  1837    -10.0
306   NaN     United Province CA  1837      2.0
307   NaN                Tuscany  1837    -10.0
308   NaN                  Baden  1837     -7.0
309   NaN                  Korea  1837      1.0
310   NaN                Bavaria  1837     -9.0
311   NaN           Two Sicilies  1837    -10.0
312   NaN                  Parma  1837    -10.0
313   NaN           Wuerttemburg  1838     -4.0
314   NaN                Bavaria  1838     -9.0
315   NaN                 Saxony  1838     -7.0
316   NaN           Two Sicilies  1838    -10.0
317   NaN                  Parma  1838    -10.0
318   NaN                 Serbia  1838      2.0
319   NaN                Tuscany  1838    -10.0
320   NaN                 Modena  1838    -10.0
321   NaN                  Korea  1838      1.0
322   NaN                  Baden  1838     -7.0
323   NaN               Sardinia  1838    -10.0
324   NaN     United Province CA  1838      2.0
325   NaN           Wuerttemburg  1839     -4.0
326   NaN                Bavaria  1839     -9.0
327   NaN                 Modena  1839    -10.0
328   NaN                 Saxony  1839     -7.0
329   NaN                  Korea  1839      1.0
330   NaN                  Parma  1839    -10.0
331   NaN                Tuscany  1839    -10.0
332   NaN           Two Sicilies  1839    -10.0
333   NaN                 Serbia  1839      2.0
334   NaN                  Baden  1839     -7.0
335   NaN               Sardinia  1839    -10.0
336   NaN                  Parma  1840    -10.0
337   NaN               Sardinia  1840    -10.0
338   NaN                  Korea  1840      1.0
339   NaN                 Modena  1840    -10.0
340   NaN           Two Sicilies  1840    -10.0
341   NaN           Wuerttemburg  1840     -4.0
342   NaN                  Baden  1840     -7.0
343   NaN                 Saxony  1840     -8.0
344   NaN                 Serbia  1840      2.0
345   NaN                Tuscany  1840    -10.0
346   NaN                Bavaria  1840     -8.0
347   NaN                Tuscany  1841    -10.0
348   NaN           Two Sicilies  1841    -10.0
349   NaN                  Korea  1841      1.0
350   NaN                  Baden  1841     -4.0
351   NaN                  Parma  1841    -10.0
352   NaN               Sardinia  1841    -10.0
353   NaN                 Modena  1841    -10.0
354   NaN                 Saxony  1841     -8.0
355   NaN                Bavaria  1841     -8.0
356   NaN           Wuerttemburg  1841     -4.0
357   NaN                 Serbia  1841      2.0
358   NaN                Bavaria  1842     -8.0
359   NaN                 Saxony  1842     -8.0
360   NaN                  Korea  1842      1.0
361   NaN               Sardinia  1842    -10.0
362   NaN           Wuerttemburg  1842     -4.0
363   NaN                 Serbia  1842      2.0
364   NaN           Two Sicilies  1842    -10.0
365   NaN                Tuscany  1842    -10.0
366   NaN                  Parma  1842    -10.0
367   NaN                  Baden  1842     -4.0
368   NaN                 Modena  1842    -10.0
369   NaN                 Serbia  1843      2.0
370   NaN                 Saxony  1843     -8.0
371   NaN                  Baden  1843     -4.0
372   NaN                  Parma  1843    -10.0
373   NaN                 Modena  1843    -10.0
374   NaN               Sardinia  1843    -10.0
375   NaN                  Korea  1843      1.0
376   NaN           Wuerttemburg  1843     -4.0
377   NaN                Tuscany  1843    -10.0
378   NaN           Two Sicilies  1843    -10.0
379   NaN                Bavaria  1843     -8.0
380   NaN           Two Sicilies  1844    -10.0
381   NaN               Sardinia  1844    -10.0
382   NaN                  Parma  1844    -10.0
383   NaN                  Baden  1844     -4.0
384   NaN                Bavaria  1844     -8.0
385   NaN                  Korea  1844      1.0
386   NaN           Wuerttemburg  1844     -4.0
387   NaN                 Serbia  1844      2.0
388   NaN                 Saxony  1844     -8.0
389   NaN                 Modena  1844    -10.0
390   NaN                Tuscany  1844    -10.0
391   NaN                 Saxony  1845     -9.0
392   NaN                 Modena  1845    -10.0
393   NaN           Wuerttemburg  1845     -4.0
394   NaN                 Serbia  1845      2.0
395   NaN                Tuscany  1845    -10.0
396   NaN                  Korea  1845      1.0
397   NaN                  Parma  1845    -10.0
398   NaN               Sardinia  1845    -10.0
399   NaN                  Baden  1845     -4.0
400   NaN                Bavaria  1845     -8.0
401   NaN           Two Sicilies  1845    -10.0
402   NaN                Bavaria  1846     -8.0
403   NaN                  Korea  1846      1.0
404   NaN                 Saxony  1846     -9.0
405   NaN           Wuerttemburg  1846     -4.0
406   NaN                 Modena  1846    -10.0
407   NaN                  Parma  1846    -10.0
408   NaN                  Baden  1846     -4.0
409   NaN           Two Sicilies  1846    -10.0
410   NaN                 Serbia  1846      2.0
411   NaN               Sardinia  1846    -10.0
412   NaN                Tuscany  1846    -10.0
413   NaN                 Saxony  1847     -9.0
414   NaN                 Modena  1847    -10.0

3g) Drop the remaining rows which have nan in "iso3" and display the new number of rows of the dataframe (how many are they?) **(1 point)**

In [564]:
# 3g

subset_iso3_clean=subset_iso3.dropna(subset=["iso3"]) #dropping NaN for missing iso3

print(subset_iso3_clean)

     iso3      country  year  polity2
1230  MNE   Montenegro  2011      9.0
1231  SRB       Serbia  2011      8.0
1233  ETH     Ethiopia  2011     -3.0
1234  SDN  Sudan-North  2011     -4.0
1235  VNM      Vietnam  2011     -7.0
1236  MNE   Montenegro  2012      9.0
1238  SRB       Serbia  2012      8.0
1239  ETH     Ethiopia  2012     -3.0
1240  VNM      Vietnam  2012     -7.0
1241  SDN  Sudan-North  2012     -4.0
1242  VNM      Vietnam  2013     -7.0
1243  MNE   Montenegro  2013      9.0
1244  SDN  Sudan-North  2013     -4.0
1245  ETH     Ethiopia  2013     -3.0
1247  SRB       Serbia  2013      8.0
1248  SRB       Serbia  2014      8.0
1249  ETH     Ethiopia  2014     -3.0
1251  MNE   Montenegro  2014      9.0
1252  SDN  Sudan-North  2014     -4.0
1253  VNM      Vietnam  2014     -7.0
1254  SRB       Serbia  2015      8.0
1255  ETH     Ethiopia  2015     -3.0
1256  SDN  Sudan-North  2015     -4.0
1258  VNM      Vietnam  2015     -7.0
1259  MNE   Montenegro  2015      9.0
1260  MNE   Montenegro  2016      9.0
1262  SDN  Sudan-North  2016     -4.0
1263  SRB       Serbia  2016      8.0
1264  VNM      Vietnam  2016     -7.0
1265  ETH     Ethiopia  2016     -3.0
1266  VNM      Vietnam  2017     -7.0
1268  ETH     Ethiopia  2017     -3.0
1269  SRB       Serbia  2017      8.0
1270  SDN  Sudan-North  2017     -4.0
1271  MNE   Montenegro  2017      9.0
1272  MNE   Montenegro  2018      9.0
1273  SDN  Sudan-North  2018     -4.0
1274  VNM      Vietnam  2018     -7.0
1275  ETH     Ethiopia  2018      1.0
1276  SRB       Serbia  2018      8.0

### Question 4: Check Polity2 <a class="anchor" id="question4"></a>

4a) Display the first and last year included in the dataset **(1 point)**

In [565]:
# 4a) first and last year in data
print(subset_iso3["year"].iloc[[0,-1]])

0       1800
1276    2018
Name: year, dtype: int32

4b) What do the values in "polity2" represent? **(1 point)**

Answer 4b:

4c) Do we have weird values for polity2? If yes, why? What should we do about them? Transform the data accordingly. **(1 point)**

Answer 4c:

In [566]:
# 4c)
(subset_iso3 == 'Not Available').sum()
Max= subset_iso3["polity2"].loc[subset_iso3["polity2"].idxmax()]
Min= subset_iso3["polity2"].loc[subset_iso3["polity2"].idxmin()]
print(Max,Min)

10.0 -10.0

4d) Make a map that shows the number of observations of polity2 by country **(1 point)**

In [567]:
# Answer 4d

4e) Store the final dataframe (the one you obtained after 4d) in an object called df_pol **(1 point)**

In [591]:
# 4e)
df_pol=subset_iso3

## Quality of Government Environmental Indicators <a class="anchor" id="qog"></a>

The QoG Environmental Indicators dataset (QoG-EI) (Povitkina, Marina, Natalia Alvarado Pachon & Cem Mert Dalli. 2021). The Quality of Government Environmental Indicators Dataset, version Sep21. University of Gothenburg: The Quality of Government Institute, https://www.gu.se/en/quality-government), is a compilation of indicators measuring countries' environmental performance over time, including the presence and stringency of environmental policies, environmental outcomes (emissions, deforestation, etc.), and public opinion on the environment. Codebook and data are available [here](https://www.gu.se/en/quality-government/qog-data/data-downloads/environmental-indicators-dataset).

### Question 5: Import the data and do few fixes <a class="anchor" id="question5"></a>

5a) Import data from the Quality of Government Environmental Indicators Dataset and display the variables types and the number of rows **(1 point)**
<br>
Hint: When you go on the webpage of the Environmental Indicators Dataset, you can directly import from a URL by copying the link address of the dataset!

In [596]:
# 5a) import new data set
url_2 = "https://www.qogdata.pol.gu.se/data/qog_ei_sept21.csv"
df_coq = pd.read_csv(url_2,encoding="latin-1") 
type(df_coq)
#encoding='latin-1'

pandas.core.frame.DataFrame

5b) Rename the variable "ccodealp" to "iso3" **(1 point)**

In [570]:
# Answer 5b

5c) Check the type of the variables "year" and "iso3" are string, if not convert them to string **(1 point)**

In [571]:
# Answer 5c

### Question 6: Merge QOG and Polity5 ... issues with QOG? <a class="anchor" id="question6"></a>

6a) Get a subset of the dataframe that includes the variables "cname", "iso3", "year" and "cckp_temp", and display the number of rows. **(1 point)**

In [572]:
# Answer 6a

6b) Merge this subset (left) and the clean version of the polity data (right), using the argument how="left". Was the merge succesfull? If yes, how many rows has the merged dataframe? Is it the same number of rows of the subset in 6a? **(1 point)**

In [573]:
# Answer 6b

6c) Do the same by adding the argument validate="one-to-one". Can you make some hypotheses on why you get an error? **(1 point)**

In [574]:
# Answer 6c

6d) Consider the subset of the QOG you obtained in 6a and write a code to (i) count the number of observations for the variable "cckp_temp" for each combination of iso3 and year, (ii) store the results in a dataframe. For example, the combination "USA-2012" should have 1 observation for "cckp_temp", so the result of your code should be 1. The code should do this for all iso3-year combinations of your subset dataframe, and store the results in a dataframe. **(1 point)**
<br>
Hint: it should not take you more than 2 lines of code.

In [575]:
# Answer 6d

6e) Use the code in 6d to write a function that displays all rows of the dataframe obtained in 6a that have more than one observation of "cckp_temp" for each iso3-year combination, and check if it works. **(1 point)**

In [576]:
# Answer 6e

6f) Which countries have more than one observation for each iso3-year combination? Deal with these countries in the subset dataframe created in 6a to make sure you no longer have double observations for iso3-year combinations, and check that after your fix this is actually the case. **(1 point)**
<br>
Hint: should we keep a country with all missing values?

In [577]:
# Answer 6f

6g) If your check went well, now you can perform the same operation directly in the QOG dataframe (not in the substed dataframe created in 6a). How many rows does now the QOG dataframe has? **(1 point)**

In [578]:
# Answer 6g

### Question 7: Merge QOG and Polity5 ... issues with Polity5? <a class="anchor" id="question7"></a>

7a) Merge the cleaned QOG dataframe (left) and the Polity dataframe (right) using the options how="left" and validate="one_to_one". Does it work? Why? **(1 point)**

In [579]:
# Answer 7a

7b) Use the function you wrote in 6e to check what's wrong in the "clean" version of Polity **(1 point)**

In [580]:
# Answer 7b

7c) Drop or fix the countries that create troubles directly in the "clean" version of Polity and motivate your choices. **(1 point)**

In [581]:
# Answer 7c

7d) Try now to merge the "clean-clean" versions of COG and Polity (the ones you obtained in 7g and 8c) always using the options how="left" and validate="one_to_one". Does it work, and why? How many rows has the resulting merged dataframe? **(1 point)**

In [582]:
# Answer 7d

### Question 8: Clean the merged dataframe <a class="anchor" id="question8"></a>

8a) In the merged dataframe, order the columns so that you have the "index" variables first and the variables with actual values last. **(1 point)**
<br>
Hint: index variables are "iso3", "year" and other similar variables you can find, and the variables with actual values are "polity2", "cckp_temp" and other similar variables you can find.

In [583]:
# Answer 8a

8b) Rename "cname" as "country" and "country" as "country_polity". **(1 point)**

In [584]:
# Answer 8b

8c) Save the clean merged dataframe as a csv in a subfolder called "clean_data" in your working directory **(1 point)**

In [585]:
# Answer 8c

## Exploratory Data Analysis <a class="anchor" id="eda"></a>

In this section you will define a research question and perform a preliminary Exploratory Data Analysis (EDA) to address - or better, start addressing - the question at hand. This exercise will be done along the lines of the analysis done by our own Quentin Gallea in "*A recipe to empirically answer any question quickly*" ([Towards Data Science, 2022](https://towardsdatascience.com/a-recipe-to-empirically-answer-any-question-quickly-22e48c867dd5)). In this article, Quentin shows the first steps of an EDA that aims to explore whether heat waves have pushed governments to implement regulations against climate change (causal link). The logic is that, as it gets hotter and hotter, governments become more aware of climate change, and the problems it can cause to society, and start addressing it. In Quentin's analysis, heat waves (proxied by temperature) is the "main explanatory variable", rainfall is the "explanatory variable for heterogeneity", and regulations against climate change (proxied by the Environmental Policy Stringency Index) is the "outcome variable". He finds that indeed countries with relatively high temperatures have implemented more regulations against climate change. This is true especially when rainfall levels are low, as when it does not rain the damage of extreme heat is more evident to legislators, who therefore apply stricter regulations against these phenomenons.
<br>
<br>
In this exercise, you will be asked to do a similar analysis on a research question of your choice, using at least two of the variables of the dataset we have created in the former questions (QOG + Polity). For example, "what is the average temperature in 2010?" is not a valid research question (univariate), while "what is the impact of high temperatures on the stringency of climate regulations?" is a valid research question (at least bivariate). As before, we will ask you some (this time more general and open) questions, and you should report your answer in the cells below each question. Use a mix of markdown and code cells to answer (markdown for text and code for graphs and tables). We should be able to run all the graphs, i.e. screenshots of graphs are not accepted. Note that for now we have put only one markdown cell and one code cell for the answer, but feel free to add as many cells as you need.
<br>
Beyond the python code, we will grade the interpretations of the results and the coding decision you make.
<br>
<br>
Let your creativity guide you and let's have some fun!

### Question 9: Selecting the ingredients (how I select the variables) <a class="anchor" id="question9"></a>
We have saved the clean merged data that resulted from the previous questions in "clean_data_prepared_EDA" (it should be the same of the one you saved in "clean_data"). Import the clean merged data from "clean_data_prepared_EDA" using this [link](https://raw.githubusercontent.com/edoardochiarotti/class_datascience/main/Notebooks/Assignment/individual_assignment/clean_data_prepared_EDA/df_qog_polity_merged.csv). Explore the variables in the newly obtained dataframe by checking the documentation of QOG and Polity. Then, define a research question that addresses a causal link between at least two of these variables. Describe the research question, why you are addressing it and the variables of interest (outcome variable, main explanatory variable and explanatory variable for heterogeneity). **(3 points)**

Answer 9:

In [586]:
# Answer 9:

### Question 10: Picking the right quantity of each ingredient (how I select my sample) <a class="anchor" id="question10"></a>
Explore the data availability of your variables of interest and select a clean sample for the analysis. Describe this sample with the help of summary-statistics tables and maps. **(3 points)**

Answer 10:

In [587]:
# Answer 10:

### Question 11: Tasting and preparing the ingredients (univariate analysis) <a class="anchor" id="question11"></a>
Do an univariate analysis for each variable you have chosen (outcome variable, main explanatory variable and explanatory variable for heterogeneity):
- Prepare the variable, for example see if you need to transform the data further, i.e. log-transform, define a categorical variable, deal with outliers, etc.
- Understand the nature of the variable, i.e. continuous, categorical, binary, etc., which then allows to pick the right statistical tool in the bivariate analysis.
- Get an idea of the variable's behaviour across time and space.

Describe these steps and the conclusions you can draw with the help of histograms, tables, maps and line graphs. **(3 points)**

Answer 11:

In [588]:
# Answer 11:

### Question 12: Cooking the ingredients together (bivariate analysis) <a class="anchor" id="question12"></a>

Considering the "nature" of your variables (continuous, categorical, binary, etc.), pick the right tool / tools for a preliminary bivariate analysis, i.e. correlation tables, bar/line graphs, scatter plots, etc. Use these tools to describe your preliminary bivariate analysis and your findings. **(3 points)**

Answer 12:

In [589]:
# Answer 12:

### Question 13: Tasting the new recipe (conclusion) <a class="anchor" id="question13"></a>

Explain what you learned, the problem faced, what would you do next (you can suggest other data you would like to have etc). **(2 points)**

Answer 13: